### ISSUE TITLE
タスク一覧

### ISSUE THREAD

**Issue by Nayuta9382** [Nayuta9382/agile_report#1]
- [x] #3
- [x] #6
- [x] #2
- [x] #8
- [x] #4
- [x] #12

**Comment by Nayuta9382** [comment]
# タイトル
## 概要
- 説明
- 説明
## メリット
- 説明
- 説明
## デメリット
- 説明
- 説明
## 重要用語の解説
### 語句
説明
### 語句
説明


## その他書き方のルール
文章中の重要語句にするものは太字で書く。

**Comment by kkudou23** [comment]
## ブランチ名のルール
dev_[名字]_#[issue番号]
例 : dev_kudou_#1
